#ifndef APPLE_II_CPU_H
#define APPLE_II_CPU_H

#include <stdint.h>

enum OPCODES {
    BRK,
    ORA_INDX,
    ORA_ZP = 0x05,
    ASL_ZP,
    PHP = 0x08,
    ORA_IM,
    ASL_AC,
    ORA_ABS = 0x0D,
    ASL_ABS,
    BPL = 0x10,
    ORA_INDY,
    ORA_ZPX = 0x15,
    ASL_ZPX,
    CLC = 0x18,
    ORA_ABSY,
    ORA_ABSX = 0x1D,
    ASL_ABSX,
    JSR = 0x20,
    AND_INDX,
    BIT_ZP = 0x24,
    AND_ZP,
    ROL_ZP,
    PLP = 0x28,
    AND_IM,
    ROL_AC,
    BIT_ABS = 0x2C,
    AND_ABS,
    ROL_ABS,
    BMI = 0x30,
    AND_INDY,
    AND_ZPX = 0x35,
    ROL_ZPX,
    SEC = 0x38,
    AND_ABSY,
    AND_ABSX = 0x3D,
    ROL_ABSX,
    RTI = 0x40,
    EOR_INDX,
    EOR_ZP = 0x45,
    LSR_ZP,
    PHA = 0x48,
    EOR_IM,
    LSR_AC,
    JMP_ABS = 0x4C,
    EOR_ABS,
    LSR_ABS,
    BVC = 0x50,
    EOR_INDY,
    EOR_ZPX = 0x55,
    LSR_ZPX,
    CLI = 0x58,
    EOR_ABSY,
    EOR_ABSX = 0x5D,
    LSR_ABSX,
    RTS = 0x60,
    ADC_INDX,
    ADC_ZP = 0x65,
    ROR_ZP,
    PLA = 0x68,
    ADC_IM,
    ROR_AC,
    JMP_IND = 0x6C,
    ADC_ABS,
    ROR_ABS,
    BVS = 0x70,
    ADC_INDY,
    ADC_ZPX = 0x75,
    ROR_ZPX,
    SEI = 0x78,
    ADC_ABSY,
    ADC_ABSX = 0x7D,
    ROR_ABSX,
    STA_INDX = 0x81,
    STY_ZP = 0x84,
    STA_ZP,
    STX_ZP,
    DEY = 0x88,
    TXA = 0x8A,
    STY_ABS = 0x8C,
    STA_ABS,
    STX_ABS,
    BCC = 0x90,
    STA_INDY,
    STY_ZPX = 0x94,
    STA_ZPX,
    STX_ZPY,
    TYA = 0x98,
    STA_ABSY,
    TXS,
    STA_ABSX = 0x9D,
    LDY_IM = 0xA0,
    LDA_INDX,
    LDX_IM,
    LDY_ZP = 0xA4,
    LDA_ZP,
    LDX_ZP,
    TAY = 0xA8,
    LDA_IM,
    TAX,
    LDY_ABS = 0xAC,
    LDA_ABS,
    LDX_ABS,
    BCS = 0xB0,
    LDA_INDY,
    LDY_ZPX = 0xB4,
    LDA_ZPX,
    LDX_ZPY,
    CLV = 0xB8,
    LDA_ABSY,
    TSX,
    LDY_ABSX = 0xBC,
    LDA_ABSX,
    LDX_ABSY,
    CPY_IM = 0xC0,
    CMP_INDX,
    CPY_ZP = 0xC4,
    CMP_ZP,
    DEC_ZP,
    INY = 0xC8,
    CMP_IM,
    DEX,
    CPY_ABS = 0xCC,
    CMP_ABS,
    DEC_ABS,
    BNE = 0xD0,
    CMP_INDY,
    CMP_ZPX = 0xD5,
    DEC_ZPX,
    CLD = 0xD8,
    CMP_ABSY,
    CMP_ABSX = 0xDD,
    DEC_ABSX,
    CPX_IM = 0xE0,
    SBC_INDX,
    CPX_ZP = 0xE4,
    SBC_ZP,
    INC_ZP,
    INX = 0xE8,
    SBC_IM,
    NOP,
    CPX_ABS = 0xEC,
    SBC_ABS,
    INC_ABS,
    BEQ = 0xF0,
    SBC_INDY,
    SBC_ZPX = 0xF5,
    INC_ZPX,
    SED = 0xF8,
    SBC_ABSY,
    SBC_ABSX = 0xFD,
    INC_ABSX,
};

uint16_t reset();

uint8_t exec();

#endif